AWSTemplateFormatVersion: '2010-09-09'
Resources:
  OrdenesVentaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: OrdenesVenta
      AttributeDefinitions:
        - AttributeName: id_orden_venta
          AttributeType: S
        - AttributeName: id_articulo
          AttributeType: S
      KeySchema:
        - AttributeName: id_orden_venta
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: ArticuloIndex
          KeySchema:
            - AttributeName: id_articulo
              KeyType: HASH
            - AttributeName: id_orden_venta
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  OrdenesVentaTableName:
    Value: !Ref OrdenesVentaTable
    Description: Tabla que contiene las órdenes de venta
